// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/etherboy-core/txmsg.proto

/*
Package txmsg is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/etherboy-core/txmsg.proto

It has these top-level messages:
	EtherboyCreateAccountTx
	EtherboyStateTx
	SimpleContractMethod
	EtherboyAppState
*/
package txmsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"
import google_protobuf "github.com/golang/protobuf/ptypes/any"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type EtherboyCreateAccountTx struct {
	// public is a json object that the dApp can look into
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EtherboyCreateAccountTx) Reset()                    { *m = EtherboyCreateAccountTx{} }
func (m *EtherboyCreateAccountTx) String() string            { return proto.CompactTextString(m) }
func (*EtherboyCreateAccountTx) ProtoMessage()               {}
func (*EtherboyCreateAccountTx) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{0} }

func (m *EtherboyCreateAccountTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type EtherboyStateTx struct {
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *EtherboyStateTx) Reset()                    { *m = EtherboyStateTx{} }
func (m *EtherboyStateTx) String() string            { return proto.CompactTextString(m) }
func (*EtherboyStateTx) ProtoMessage()               {}
func (*EtherboyStateTx) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{1} }

func (m *EtherboyStateTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type SimpleContractMethod struct {
	// version to help upgrades to code
	Version int32                `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Owner   string               `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Method  string               `protobuf:"bytes,3,opt,name=method,proto3" json:"method,omitempty"`
	Data    *google_protobuf.Any `protobuf:"bytes,4,opt,name=data" json:"data,omitempty"`
}

func (m *SimpleContractMethod) Reset()                    { *m = SimpleContractMethod{} }
func (m *SimpleContractMethod) String() string            { return proto.CompactTextString(m) }
func (*SimpleContractMethod) ProtoMessage()               {}
func (*SimpleContractMethod) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{2} }

func (m *SimpleContractMethod) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *SimpleContractMethod) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *SimpleContractMethod) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *SimpleContractMethod) GetData() *google_protobuf.Any {
	if m != nil {
		return m.Data
	}
	return nil
}

type EtherboyAppState struct {
	Address []byte `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Blob    []byte `protobuf:"bytes,2,opt,name=blob,proto3" json:"blob,omitempty"`
}

func (m *EtherboyAppState) Reset()                    { *m = EtherboyAppState{} }
func (m *EtherboyAppState) String() string            { return proto.CompactTextString(m) }
func (*EtherboyAppState) ProtoMessage()               {}
func (*EtherboyAppState) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{3} }

func (m *EtherboyAppState) GetAddress() []byte {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *EtherboyAppState) GetBlob() []byte {
	if m != nil {
		return m.Blob
	}
	return nil
}

func init() {
	proto.RegisterType((*EtherboyCreateAccountTx)(nil), "EtherboyCreateAccountTx")
	proto.RegisterType((*EtherboyStateTx)(nil), "EtherboyStateTx")
	proto.RegisterType((*SimpleContractMethod)(nil), "SimpleContractMethod")
	proto.RegisterType((*EtherboyAppState)(nil), "EtherboyAppState")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/etherboy-core/txmsg.proto", fileDescriptorTxmsg)
}

var fileDescriptorTxmsg = []byte{
	// 264 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x8f, 0xd1, 0x4e, 0x83, 0x30,
	0x14, 0x86, 0x83, 0x6e, 0x33, 0xd6, 0x25, 0x9a, 0x86, 0x28, 0x7a, 0x45, 0x96, 0x98, 0x70, 0x33,
	0x30, 0xfa, 0x02, 0x92, 0xc5, 0x4b, 0x6f, 0x98, 0x2f, 0xd0, 0xc2, 0x11, 0x88, 0xb4, 0x87, 0x94,
	0x83, 0x1b, 0x6f, 0xe0, 0x63, 0x9b, 0x95, 0xf6, 0x72, 0x77, 0xe7, 0x6b, 0xff, 0xd3, 0x7e, 0x3f,
	0x7b, 0xa9, 0x5b, 0x6a, 0x46, 0x99, 0x96, 0xa8, 0xb2, 0x0e, 0x51, 0x69, 0xa0, 0x03, 0x9a, 0x9f,
	0x0c, 0xa8, 0x01, 0x23, 0x71, 0xda, 0x96, 0x68, 0x20, 0xa3, 0xa3, 0x1a, 0xea, 0xb4, 0x37, 0x48,
	0xf8, 0xf4, 0x58, 0x23, 0xd6, 0x1d, 0x64, 0x96, 0xe4, 0xf8, 0x9d, 0x09, 0x3d, 0xcd, 0x57, 0x9b,
	0x2d, 0x7b, 0xf8, 0x70, 0x7b, 0x3b, 0x03, 0x82, 0x20, 0x2f, 0x4b, 0x1c, 0x35, 0x7d, 0x1d, 0x39,
	0x67, 0x8b, 0x4a, 0x90, 0x88, 0x82, 0x38, 0x48, 0xd6, 0x85, 0x9d, 0x37, 0xcf, 0xec, 0xd6, 0xc7,
	0xf7, 0x24, 0x08, 0xce, 0xc4, 0xfe, 0x02, 0x16, 0xee, 0x5b, 0xd5, 0x77, 0xb0, 0x43, 0x4d, 0x46,
	0x94, 0xf4, 0x09, 0xd4, 0x60, 0xc5, 0x23, 0x76, 0xf5, 0x0b, 0x66, 0x68, 0x51, 0xdb, 0xfc, 0xb2,
	0xf0, 0xc8, 0x43, 0xb6, 0xc4, 0x83, 0x06, 0x13, 0x5d, 0xc4, 0x41, 0x72, 0x5d, 0xcc, 0xc0, 0xef,
	0xd9, 0x4a, 0xd9, 0xcd, 0xe8, 0xd2, 0x1e, 0x3b, 0xe2, 0x89, 0xfb, 0x74, 0x11, 0x07, 0xc9, 0xcd,
	0x6b, 0x98, 0xce, 0x05, 0x53, 0x5f, 0x30, 0xcd, 0xf5, 0xe4, 0x54, 0xde, 0xd9, 0x9d, 0x37, 0xce,
	0xfb, 0xde, 0x4a, 0x9f, 0x2c, 0x44, 0x55, 0x19, 0x18, 0x06, 0x67, 0xed, 0xf1, 0x54, 0x46, 0x76,
	0x28, 0xad, 0xc4, 0xba, 0xb0, 0xb3, 0x5c, 0xd9, 0x57, 0xdf, 0xfe, 0x03, 0x00, 0x00, 0xff, 0xff,
	0x73, 0xb1, 0xf3, 0x95, 0x78, 0x01, 0x00, 0x00,
}
