// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: github.com/loomnetwork/etherboy-core/testdata/test.proto

/*
Package testdata is a generated protocol buffer package.

It is generated from these files:
	github.com/loomnetwork/etherboy-core/testdata/test.proto

It has these top-level messages:
	FakeQueryParams
	FakeQueryResult
*/
package testdata

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type FakeQueryParams struct {
	Key   string `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value int32  `protobuf:"varint,2,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *FakeQueryParams) Reset()                    { *m = FakeQueryParams{} }
func (m *FakeQueryParams) String() string            { return proto.CompactTextString(m) }
func (*FakeQueryParams) ProtoMessage()               {}
func (*FakeQueryParams) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{0} }

func (m *FakeQueryParams) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *FakeQueryParams) GetValue() int32 {
	if m != nil {
		return m.Value
	}
	return 0
}

type FakeQueryResult struct {
	Value string `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
}

func (m *FakeQueryResult) Reset()                    { *m = FakeQueryResult{} }
func (m *FakeQueryResult) String() string            { return proto.CompactTextString(m) }
func (*FakeQueryResult) ProtoMessage()               {}
func (*FakeQueryResult) Descriptor() ([]byte, []int) { return fileDescriptorTest, []int{1} }

func (m *FakeQueryResult) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

func init() {
	proto.RegisterType((*FakeQueryParams)(nil), "testdata.FakeQueryParams")
	proto.RegisterType((*FakeQueryResult)(nil), "testdata.FakeQueryResult")
}

func init() {
	proto.RegisterFile("github.com/loomnetwork/etherboy-core/testdata/test.proto", fileDescriptorTest)
}

var fileDescriptorTest = []byte{
	// 156 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xb2, 0x48, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0xcf, 0xc9, 0xcf, 0xcf, 0xcd, 0x4b, 0x2d, 0x29, 0xcf,
	0x2f, 0xca, 0xd6, 0x4f, 0x2d, 0xc9, 0x48, 0x2d, 0x4a, 0xca, 0xaf, 0xd4, 0x4d, 0xce, 0x2f, 0x4a,
	0xd5, 0x2f, 0x49, 0x2d, 0x2e, 0x49, 0x49, 0x2c, 0x49, 0x04, 0x33, 0xf4, 0x0a, 0x8a, 0xf2, 0x4b,
	0xf2, 0x85, 0x38, 0x60, 0x82, 0x4a, 0x96, 0x5c, 0xfc, 0x6e, 0x89, 0xd9, 0xa9, 0x81, 0xa5, 0xa9,
	0x45, 0x95, 0x01, 0x89, 0x45, 0x89, 0xb9, 0xc5, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x12,
	0x8c, 0x0a, 0x8c, 0x1a, 0x9c, 0x41, 0x20, 0xa6, 0x90, 0x08, 0x17, 0x6b, 0x59, 0x62, 0x4e, 0x69,
	0xaa, 0x04, 0x93, 0x02, 0xa3, 0x06, 0x6b, 0x10, 0x84, 0xa3, 0xa4, 0x8e, 0xa4, 0x35, 0x28, 0xb5,
	0xb8, 0x34, 0xa7, 0x04, 0xa1, 0x10, 0xa2, 0x19, 0xc2, 0x49, 0x62, 0x03, 0x5b, 0x6a, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x8b, 0x4a, 0x38, 0x2f, 0xb0, 0x00, 0x00, 0x00,
}
